In [1]:
## Basic imports 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

%matplotlib inline

warnings.filterwarnings('ignore')

In [2]:
## import models

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

In [3]:
df = pd.read_csv('data/Cleaned_Brain_Stroke.csv')
df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1

In [4]:
X = df.drop('stroke',axis=1)
y = df['stroke']

In [5]:
X.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked

In [6]:
y

0       1
1       1
2       1
3       1
4       1
       ..
4976    0
4977    0
4978    0
4979    0
4980    0
Name: stroke, Length: 4981, dtype: int64

In [7]:
cat_fea = X.select_dtypes(include='object').columns
num_fea = X.select_dtypes(exclude='object').columns

print(f"Categorical features are {cat_fea}")
print(f"Numerical features are {num_fea}")

Categorical features are Index(['gender', 'ever_married', 'work_type', 'Residence_type',
       'smoking_status'],
      dtype='object')
Numerical features are Index(['age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi'], dtype='object')

In [8]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

In [9]:
oh_encode = OneHotEncoder()
std_scaler = StandardScaler()

preprocessor = ColumnTransformer([
    ('OneHotEncoder',oh_encode,cat_fea),
    ('StandardScaler',std_scaler,num_fea)
])

In [10]:
X = preprocessor.fit_transform(X)

In [11]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.040584,-0.326186,4.136753,2.723411,1.193238
1,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.614270,-0.326186,4.136753,-0.000523,0.589390
2,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.246250,-0.326186,-0.241735,1.448529,0.869222
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.570141,3.065738,-0.241735,1.512650,-0.662492
4,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.658400,-0.326186,-0.241735,1.780895,0.073909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4976,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,-0.106788,-0.326186,-0.241735,-0.794162,0.191733
4977,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.150917,-0.326186,-0.241735,1.890500,0.383197
4978,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.069731,3.065738,-0.241735,-0.242364,0.486294
4979,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,-0.150917,-0.326186,-0.241735,-0.488199,0.221189
4980,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.614270,3.065738,-0.241735,-0.492415,0.088637

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [13]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.202120,-0.326186,-0.241735,-0.629976,-0.338475
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,-1.827846,-0.326186,4.136753,-0.955242,0.132821
2,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.775806,-0.326186,-0.241735,-0.265661,1.605623
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.334509,3.065738,-0.241735,1.509100,0.397925
4,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.261233,-0.326186,-0.241735,-0.042013,0.736670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3730,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.466898,-0.326186,-0.241735,2.786645,0.206461
3731,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.239177,-0.326186,-0.241735,-0.777078,1.929639
3732,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-1.342419,-0.326186,-0.241735,-0.340432,-1.708180
3733,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,-1.894923,-0.326186,-0.241735,0.284140,-1.634540
3734,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.599287,-0.326186,-0.241735,0.495585,0.839766

In [14]:
def model_evalution(true,predicted):
    acc = accuracy_score(true,predicted)
    pre = precision_score(true,predicted)
    recall = recall_score(true,predicted)
    f1 = f1_score(true,predicted)

    return acc,pre,recall,f1

In [15]:
models = {
    'Logistic Regression' :LogisticRegression(),
    'KNeighbors Classifier' :KNeighborsClassifier(),
    'DecisionTree Classifier' : DecisionTreeClassifier(),
    'SVC' : SVC(),
    'RandomForest Classifier' : RandomForestClassifier(),
    'AdaBoost Classifier' :AdaBoostClassifier(),
    'XGB Classifier' : XGBClassifier(),
    'CatBoostClassifier' :CatBoostClassifier(),
}

model_list = []
accuracy_score_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)

    accuracy_score_train, precision_score_train, recall_score_train, f1_score_train = model_evalution(y_train,y_pred_train)
    accuracy_score_test, precision_score_test, recall_score_test, f1_score_test = model_evalution(y_test,y_pred_test)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print("Model Performance for Training set")
    print("-Accuracy score {:.4f}".format(accuracy_score_train))
    print("-Precision score {:.4f}".format(precision_score_train))
    print("-Recall score {:.4f}".format(recall_score_train))
    print("-F1 score {:.4f}".format(f1_score_train))

    print("-"*35)

    print("Model Performance for Testing set")
    print("-Accuracy score {:.4f}".format(accuracy_score_test))
    print("-Precision score {:.4f}".format(precision_score_test))
    print("-Recall score {:.4f}".format(recall_score_test))
    print("-F1 score {:.4f}".format(f1_score_test))
    accuracy_score_list.append(accuracy_score_test)

    print("="*35)
    print("\n")

Logistic Regression
Model Performance for Training set
-Accuracy score 0.9521
-Precision score 0.0000
-Recall score 0.0000
-F1 score 0.0000
-----------------------------------
Model Performance for Testing set
-Accuracy score 0.9446
-Precision score 0.0000
-Recall score 0.0000
-F1 score 0.0000
===================================


KNeighbors Classifier
Model Performance for Training set
-Accuracy score 0.9523
-Precision score 0.5263
-Recall score 0.0559
-F1 score 0.1010
-----------------------------------
Model Performance for Testing set
-Accuracy score 0.9406
-Precision score 0.1429
-Recall score 0.0145
-F1 score 0.0263
===================================


DecisionTree Classifier
Model Performance for Training set
-Accuracy score 1.0000
-Precision score 1.0000
-Recall score 1.0000
-F1 score 1.0000
-----------------------------------
Model Performance for Testing set
-Accuracy score 0.9013
-Precision score 0.1029
-Recall score 0.1014
-F1 score 0.1022
===================================


SVC
Model Performance for Training set
-Accuracy score 0.9521
-Precision score 0.0000
-Recall score 0.0000
-F1 score 0.0000
-----------------------------------
Model Performance for Testing set
-Accuracy score 0.9446
-Precision score 0.0000
-Recall score 0.0000
-F1 score 0.0000
===================================


RandomForest Classifier
Model Performance for Training set
-Accuracy score 1.0000
-Precision score 1.0000
-Recall score 1.0000
-F1 score 1.0000
-----------------------------------
Model Performance for Testing set
-Accuracy score 0.9406
-Precision score 0.0000
-Recall score 0.0000
-F1 score 0.0000
===================================


AdaBoost Classifier
Model Performance for Training set
-Accuracy score 0.9521
-Precision score 0.0000
-Recall score 0.0000
-F1 score 0.0000
-----------------------------------
Model Performance for Testing set
-Accuracy score 0.9446
-Precision score 0.0000
-Recall score 0.0000
-F1 score 0.0000
===================================


XGB Classifier
Model Performance for Training set
-Accuracy score 0.9995
-Precision score 1.0000
-Recall score 0.9888
-F1 score 0.9944
-----------------------------------
Model Performance for Testing set
-Accuracy score 0.9406
-Precision score 0.2727
-Recall score 0.0435
-F1 score 0.0750
===================================


Learning rate set to 0.018084
0:	learn: 0.6652749	total: 149ms	remaining: 2m 28s
1:	learn: 0.6402541	total: 151ms	remaining: 1m 15s
2:	learn: 0.6175868	total: 154ms	remaining: 51.1s
3:	learn: 0.5943834	total: 155ms	remaining: 38.7s
4:	learn: 0.5740730	total: 158ms	remaining: 31.4s
5:	learn: 0.5532356	total: 160ms	remaining: 26.5s
6:	learn: 0.5348637	total: 162ms	remaining: 23s
7:	learn: 0.5162519	total: 164ms	remaining: 20.4s
8:	learn: 0.4968740	total: 166ms	remaining: 18.3s
9:	learn: 0.4752547	total: 169ms	remaining: 16.7s
10:	learn: 0.4593296	total: 171ms	remaining: 15.3s
11:	learn: 0.4413758	total: 173ms	remaining: 14.2s
12:	learn: 0.4278331	total: 175ms	remaining: 13.3s
13:	learn: 0.4113123	total: 177ms	remaining: 12.5s
14:	learn: 0.3966901	total: 179ms	remaining: 11.8s
15:	learn: 0.3835628	total: 181ms	remaining: 11.2s
16:	learn: 0.3720925	total: 185ms	remaining: 10.7s
17:	learn: 0.3587340	total: 188ms	remaining: 10.2s
18:	learn: 0.3491546	total: 189ms	remaining: 9.77s
19:	learn: 0.3401923	total: 191ms	remaining: 9.38s
20:	learn: 0.3319975	total: 194ms	remaining: 9.02s
21:	learn: 0.3237980	total: 196ms	remaining: 8.7s
22:	learn: 0.3171272	total: 197ms	remaining: 8.37s
23:	learn: 0.3077521	total: 199ms	remaining: 8.09s
24:	learn: 0.3009653	total: 201ms	remaining: 7.82s
25:	learn: 0.2953592	total: 202ms	remaining: 7.55s
26:	learn: 0.2894944	total: 204ms	remaining: 7.34s
27:	learn: 0.2841853	total: 206ms	remaining: 7.13s
28:	learn: 0.2781540	total: 208ms	remaining: 6.96s
29:	learn: 0.2715720	total: 210ms	remaining: 6.79s
30:	learn: 0.2656215	total: 212ms	remaining: 6.64s
31:	learn: 0.2593824	total: 215ms	remaining: 6.49s
32:	learn: 0.2544782	total: 217ms	remaining: 6.36s
33:	learn: 0.2506125	total: 219ms	remaining: 6.23s
34:	learn: 0.2451488	total: 221ms	remaining: 6.1s
35:	learn: 0.2403260	total: 224ms	remaining: 5.99s
36:	learn: 0.2368789	total: 226ms	remaining: 5.87s
37:	learn: 0.2328155	total: 228ms	remaining: 5.77s
38:	learn: 0.2289364	total: 231ms	remaining: 5.69s
39:	learn: 0.2253158	total: 233ms	remaining: 5.6s
40:	learn: 0.2226240	total: 236ms	remaining: 5.51s
41:	learn: 0.2195925	total: 238ms	remaining: 5.42s
42:	learn: 0.2164242	total: 240ms	remaining: 5.34s
43:	learn: 0.2131656	total: 242ms	remaining: 5.26s
44:	learn: 0.2108338	total: 245ms	remaining: 5.19s
45:	learn: 0.2083839	total: 247ms	remaining: 5.13s
46:	learn: 0.2052089	total: 249ms	remaining: 5.05s
47:	learn: 0.2033731	total: 251ms	remaining: 4.98s
48:	learn: 0.2014132	total: 254ms	remaining: 4.92s
49:	learn: 0.1993306	total: 256ms	remaining: 4.86s
50:	learn: 0.1973354	total: 258ms	remaining: 4.79s
51:	learn: 0.1952146	total: 260ms	remaining: 4.74s
52:	learn: 0.1936950	total: 261ms	remaining: 4.67s
53:	learn: 0.1923912	total: 263ms	remaining: 4.61s
54:	learn: 0.1911736	total: 265ms	remaining: 4.55s
55:	learn: 0.1895733	total: 267ms	remaining: 4.5s
56:	learn: 0.1879883	total: 269ms	remaining: 4.45s
57:	learn: 0.1859864	total: 271ms	remaining: 4.41s
58:	learn: 0.1841547	total: 273ms	remaining: 4.36s
59:	learn: 0.1828430	total: 275ms	remaining: 4.31s
60:	learn: 0.1812588	total: 278ms	remaining: 4.27s
61:	learn: 0.1803422	total: 280ms	remaining: 4.23s
62:	learn: 0.1791692	total: 282ms	remaining: 4.19s
63:	learn: 0.1781023	total: 284ms	remaining: 4.15s
64:	learn: 0.1773738	total: 286ms	remaining: 4.12s
65:	learn: 0.1763219	total: 288ms	remaining: 4.08s
66:	learn: 0.1756310	total: 290ms	remaining: 4.04s
67:	learn: 0.1745366	total: 292ms	remaining: 4.01s
68:	learn: 0.1732211	total: 295ms	remaining: 3.98s
69:	learn: 0.1720579	total: 297ms	remaining: 3.94s
70:	learn: 0.1714934	total: 299ms	remaining: 3.91s
71:	learn: 0.1701556	total: 301ms	remaining: 3.88s
72:	learn: 0.1693100	total: 303ms	remaining: 3.85s
73:	learn: 0.1683481	total: 305ms	remaining: 3.81s
74:	learn: 0.1674095	total: 307ms	remaining: 3.78s
75:	learn: 0.1666434	total: 309ms	remaining: 3.75s
76:	learn: 0.1660933	total: 311ms	remaining: 3.72s
77:	learn: 0.1649503	total: 313ms	remaining: 3.7s
78:	learn: 0.1640190	total: 315ms	remaining: 3.67s
79:	learn: 0.1632044	total: 317ms	remaining: 3.64s
80:	learn: 0.1627157	total: 319ms	remaining: 3.62s
81:	learn: 0.1618797	total: 321ms	remaining: 3.59s
82:	learn: 0.1612932	total: 323ms	remaining: 3.56s
83:	learn: 0.1604835	total: 325ms	remaining: 3.54s
84:	learn: 0.1596937	total: 327ms	remaining: 3.52s
85:	learn: 0.1590153	total: 329ms	remaining: 3.5s
86:	learn: 0.1582263	total: 331ms	remaining: 3.48s
87:	learn: 0.1575276	total: 333ms	remaining: 3.45s
88:	learn: 0.1569226	total: 335ms	remaining: 3.43s
89:	learn: 0.1562996	total: 337ms	remaining: 3.41s
90:	learn: 0.1557556	total: 339ms	remaining: 3.38s
91:	learn: 0.1552016	total: 341ms	remaining: 3.37s
92:	learn: 0.1546359	total: 344ms	remaining: 3.36s
93:	learn: 0.1541647	total: 346ms	remaining: 3.34s
94:	learn: 0.1536856	total: 348ms	remaining: 3.32s
95:	learn: 0.1532052	total: 350ms	remaining: 3.3s
96:	learn: 0.1530585	total: 351ms	remaining: 3.27s
97:	learn: 0.1526061	total: 353ms	remaining: 3.25s
98:	learn: 0.1520155	total: 355ms	remaining: 3.23s
99:	learn: 0.1515840	total: 357ms	remaining: 3.22s
100:	learn: 0.1512082	total: 360ms	remaining: 3.2s
101:	learn: 0.1511220	total: 361ms	remaining: 3.18s
102:	learn: 0.1505233	total: 363ms	remaining: 3.16s
103:	learn: 0.1502061	total: 365ms	remaining: 3.15s
104:	learn: 0.1497260	total: 368ms	remaining: 3.13s
105:	learn: 0.1493239	total: 370ms	remaining: 3.12s
106:	learn: 0.1490692	total: 373ms	remaining: 3.11s
107:	learn: 0.1486721	total: 375ms	remaining: 3.1s
108:	learn: 0.1482957	total: 378ms	remaining: 3.09s
109:	learn: 0.1480547	total: 381ms	remaining: 3.08s
110:	learn: 0.1477200	total: 383ms	remaining: 3.06s
111:	learn: 0.1473630	total: 385ms	remaining: 3.05s
112:	learn: 0.1469660	total: 387ms	remaining: 3.04s
113:	learn: 0.1466380	total: 390ms	remaining: 3.03s
114:	learn: 0.1463636	total: 392ms	remaining: 3.02s
115:	learn: 0.1461826	total: 394ms	remaining: 3s
116:	learn: 0.1458986	total: 396ms	remaining: 2.99s
117:	learn: 0.1456450	total: 398ms	remaining: 2.98s
118:	learn: 0.1453773	total: 400ms	remaining: 2.96s
119:	learn: 0.1451047	total: 402ms	remaining: 2.95s
120:	learn: 0.1447641	total: 404ms	remaining: 2.94s
121:	learn: 0.1445024	total: 407ms	remaining: 2.93s
122:	learn: 0.1443073	total: 408ms	remaining: 2.91s
123:	learn: 0.1441414	total: 411ms	remaining: 2.9s
124:	learn: 0.1437710	total: 412ms	remaining: 2.89s
125:	learn: 0.1435595	total: 414ms	remaining: 2.87s
126:	learn: 0.1433168	total: 416ms	remaining: 2.86s
127:	learn: 0.1431815	total: 418ms	remaining: 2.85s
128:	learn: 0.1429857	total: 421ms	remaining: 2.84s
129:	learn: 0.1427483	total: 423ms	remaining: 2.83s
130:	learn: 0.1425412	total: 426ms	remaining: 2.82s
131:	learn: 0.1423101	total: 427ms	remaining: 2.81s
132:	learn: 0.1420370	total: 429ms	remaining: 2.8s
133:	learn: 0.1417775	total: 431ms	remaining: 2.79s
134:	learn: 0.1415908	total: 434ms	remaining: 2.78s
135:	learn: 0.1412387	total: 436ms	remaining: 2.77s
136:	learn: 0.1409802	total: 439ms	remaining: 2.76s
137:	learn: 0.1407346	total: 441ms	remaining: 2.75s
138:	learn: 0.1404728	total: 443ms	remaining: 2.74s
139:	learn: 0.1402245	total: 445ms	remaining: 2.73s
140:	learn: 0.1400157	total: 448ms	remaining: 2.73s
141:	learn: 0.1396841	total: 450ms	remaining: 2.72s
142:	learn: 0.1395111	total: 452ms	remaining: 2.71s
143:	learn: 0.1393229	total: 455ms	remaining: 2.7s
144:	learn: 0.1390621	total: 457ms	remaining: 2.69s
145:	learn: 0.1388660	total: 459ms	remaining: 2.68s
146:	learn: 0.1386739	total: 461ms	remaining: 2.67s
147:	learn: 0.1385159	total: 463ms	remaining: 2.66s
148:	learn: 0.1382727	total: 465ms	remaining: 2.65s
149:	learn: 0.1380324	total: 467ms	remaining: 2.65s
150:	learn: 0.1378270	total: 469ms	remaining: 2.64s
151:	learn: 0.1376538	total: 471ms	remaining: 2.63s
152:	learn: 0.1374737	total: 473ms	remaining: 2.62s
153:	learn: 0.1371813	total: 475ms	remaining: 2.61s
154:	learn: 0.1369941	total: 477ms	remaining: 2.6s
155:	learn: 0.1368412	total: 480ms	remaining: 2.59s
156:	learn: 0.1366432	total: 481ms	remaining: 2.58s
157:	learn: 0.1363980	total: 484ms	remaining: 2.58s
158:	learn: 0.1361489	total: 486ms	remaining: 2.57s
159:	learn: 0.1359906	total: 488ms	remaining: 2.56s
160:	learn: 0.1358134	total: 491ms	remaining: 2.56s
161:	learn: 0.1357200	total: 493ms	remaining: 2.55s
162:	learn: 0.1354704	total: 495ms	remaining: 2.54s
163:	learn: 0.1353049	total: 497ms	remaining: 2.53s
164:	learn: 0.1351207	total: 499ms	remaining: 2.52s
165:	learn: 0.1348992	total: 501ms	remaining: 2.52s
166:	learn: 0.1346365	total: 504ms	remaining: 2.51s
167:	learn: 0.1344480	total: 506ms	remaining: 2.5s
168:	learn: 0.1342087	total: 508ms	remaining: 2.5s
169:	learn: 0.1340429	total: 510ms	remaining: 2.49s
170:	learn: 0.1338386	total: 512ms	remaining: 2.48s
171:	learn: 0.1336162	total: 514ms	remaining: 2.47s
172:	learn: 0.1334209	total: 516ms	remaining: 2.47s
173:	learn: 0.1332073	total: 519ms	remaining: 2.46s
174:	learn: 0.1330520	total: 521ms	remaining: 2.46s
175:	learn: 0.1329529	total: 523ms	remaining: 2.45s
176:	learn: 0.1328113	total: 525ms	remaining: 2.44s
177:	learn: 0.1326421	total: 527ms	remaining: 2.44s
178:	learn: 0.1325269	total: 530ms	remaining: 2.43s
179:	learn: 0.1323276	total: 533ms	remaining: 2.43s
180:	learn: 0.1322722	total: 535ms	remaining: 2.42s
181:	learn: 0.1321463	total: 537ms	remaining: 2.41s
182:	learn: 0.1320636	total: 539ms	remaining: 2.41s
183:	learn: 0.1318918	total: 542ms	remaining: 2.4s
184:	learn: 0.1317060	total: 544ms	remaining: 2.4s
185:	learn: 0.1315645	total: 546ms	remaining: 2.39s
186:	learn: 0.1314304	total: 549ms	remaining: 2.38s
187:	learn: 0.1312500	total: 551ms	remaining: 2.38s
188:	learn: 0.1310587	total: 554ms	remaining: 2.38s
189:	learn: 0.1308972	total: 556ms	remaining: 2.37s
190:	learn: 0.1307783	total: 558ms	remaining: 2.36s
191:	learn: 0.1306993	total: 560ms	remaining: 2.36s
192:	learn: 0.1305338	total: 563ms	remaining: 2.35s
193:	learn: 0.1303417	total: 565ms	remaining: 2.35s
194:	learn: 0.1301118	total: 568ms	remaining: 2.34s
195:	learn: 0.1299831	total: 570ms	remaining: 2.34s
196:	learn: 0.1297877	total: 572ms	remaining: 2.33s
197:	learn: 0.1296519	total: 574ms	remaining: 2.33s
198:	learn: 0.1294842	total: 576ms	remaining: 2.32s
199:	learn: 0.1294346	total: 579ms	remaining: 2.31s
200:	learn: 0.1292323	total: 581ms	remaining: 2.31s
201:	learn: 0.1290994	total: 583ms	remaining: 2.3s
202:	learn: 0.1289085	total: 585ms	remaining: 2.3s
203:	learn: 0.1287712	total: 587ms	remaining: 2.29s
204:	learn: 0.1285704	total: 589ms	remaining: 2.29s
205:	learn: 0.1284094	total: 592ms	remaining: 2.28s
206:	learn: 0.1282433	total: 594ms	remaining: 2.28s
207:	learn: 0.1281417	total: 597ms	remaining: 2.27s
208:	learn: 0.1279552	total: 599ms	remaining: 2.27s
209:	learn: 0.1278356	total: 601ms	remaining: 2.26s
210:	learn: 0.1276708	total: 604ms	remaining: 2.26s
211:	learn: 0.1275211	total: 606ms	remaining: 2.25s
212:	learn: 0.1273680	total: 608ms	remaining: 2.24s
213:	learn: 0.1272845	total: 610ms	remaining: 2.24s
214:	learn: 0.1271828	total: 612ms	remaining: 2.23s
215:	learn: 0.1271107	total: 614ms	remaining: 2.23s
216:	learn: 0.1270115	total: 616ms	remaining: 2.22s
217:	learn: 0.1268618	total: 618ms	remaining: 2.22s
218:	learn: 0.1267192	total: 620ms	remaining: 2.21s
219:	learn: 0.1266197	total: 622ms	remaining: 2.21s
220:	learn: 0.1264899	total: 624ms	remaining: 2.2s
221:	learn: 0.1263628	total: 626ms	remaining: 2.19s
222:	learn: 0.1263120	total: 629ms	remaining: 2.19s
223:	learn: 0.1261811	total: 631ms	remaining: 2.19s
224:	learn: 0.1260250	total: 633ms	remaining: 2.18s
225:	learn: 0.1259221	total: 635ms	remaining: 2.17s
226:	learn: 0.1257774	total: 637ms	remaining: 2.17s
227:	learn: 0.1255863	total: 638ms	remaining: 2.16s
228:	learn: 0.1254967	total: 640ms	remaining: 2.15s
229:	learn: 0.1252894	total: 643ms	remaining: 2.15s
230:	learn: 0.1251415	total: 645ms	remaining: 2.15s
231:	learn: 0.1250320	total: 647ms	remaining: 2.14s
232:	learn: 0.1249137	total: 649ms	remaining: 2.13s
233:	learn: 0.1247954	total: 651ms	remaining: 2.13s
234:	learn: 0.1246659	total: 653ms	remaining: 2.12s
235:	learn: 0.1245599	total: 655ms	remaining: 2.12s
236:	learn: 0.1244391	total: 657ms	remaining: 2.11s
237:	learn: 0.1243304	total: 659ms	remaining: 2.11s
238:	learn: 0.1242168	total: 661ms	remaining: 2.1s
239:	learn: 0.1241407	total: 663ms	remaining: 2.1s
240:	learn: 0.1239082	total: 665ms	remaining: 2.1s
241:	learn: 0.1237962	total: 667ms	remaining: 2.09s
242:	learn: 0.1237114	total: 669ms	remaining: 2.08s
243:	learn: 0.1236341	total: 671ms	remaining: 2.08s
244:	learn: 0.1234321	total: 674ms	remaining: 2.08s
245:	learn: 0.1233790	total: 676ms	remaining: 2.07s
246:	learn: 0.1232295	total: 678ms	remaining: 2.07s
247:	learn: 0.1231447	total: 680ms	remaining: 2.06s
248:	learn: 0.1229776	total: 682ms	remaining: 2.06s
249:	learn: 0.1228870	total: 683ms	remaining: 2.05s
250:	learn: 0.1227662	total: 685ms	remaining: 2.04s
251:	learn: 0.1226552	total: 687ms	remaining: 2.04s
252:	learn: 0.1225457	total: 690ms	remaining: 2.04s
253:	learn: 0.1223885	total: 692ms	remaining: 2.03s
254:	learn: 0.1222774	total: 694ms	remaining: 2.03s
255:	learn: 0.1221373	total: 696ms	remaining: 2.02s
256:	learn: 0.1220310	total: 698ms	remaining: 2.02s
257:	learn: 0.1219307	total: 700ms	remaining: 2.01s
258:	learn: 0.1217629	total: 702ms	remaining: 2.01s
259:	learn: 0.1215942	total: 704ms	remaining: 2s
260:	learn: 0.1214820	total: 706ms	remaining: 2s
261:	learn: 0.1213350	total: 708ms	remaining: 2s
262:	learn: 0.1212011	total: 710ms	remaining: 1.99s
263:	learn: 0.1210825	total: 712ms	remaining: 1.99s
264:	learn: 0.1209570	total: 714ms	remaining: 1.98s
265:	learn: 0.1208289	total: 716ms	remaining: 1.98s
266:	learn: 0.1207528	total: 718ms	remaining: 1.97s
267:	learn: 0.1205847	total: 720ms	remaining: 1.97s
268:	learn: 0.1204291	total: 722ms	remaining: 1.96s
269:	learn: 0.1203159	total: 724ms	remaining: 1.96s
270:	learn: 0.1202011	total: 726ms	remaining: 1.95s
271:	learn: 0.1201071	total: 729ms	remaining: 1.95s
272:	learn: 0.1200578	total: 731ms	remaining: 1.95s
273:	learn: 0.1199439	total: 733ms	remaining: 1.94s
274:	learn: 0.1198894	total: 736ms	remaining: 1.94s
275:	learn: 0.1197716	total: 738ms	remaining: 1.94s
276:	learn: 0.1196266	total: 740ms	remaining: 1.93s
277:	learn: 0.1195207	total: 742ms	remaining: 1.93s
278:	learn: 0.1194011	total: 744ms	remaining: 1.92s
279:	learn: 0.1193373	total: 746ms	remaining: 1.92s
280:	learn: 0.1192365	total: 749ms	remaining: 1.92s
281:	learn: 0.1191221	total: 751ms	remaining: 1.91s
282:	learn: 0.1190385	total: 754ms	remaining: 1.91s
283:	learn: 0.1188821	total: 756ms	remaining: 1.91s
284:	learn: 0.1188022	total: 758ms	remaining: 1.9s
285:	learn: 0.1187075	total: 760ms	remaining: 1.9s
286:	learn: 0.1186376	total: 763ms	remaining: 1.89s
287:	learn: 0.1185260	total: 765ms	remaining: 1.89s
288:	learn: 0.1183234	total: 767ms	remaining: 1.89s
289:	learn: 0.1181842	total: 769ms	remaining: 1.88s
290:	learn: 0.1180780	total: 771ms	remaining: 1.88s
291:	learn: 0.1179648	total: 773ms	remaining: 1.88s
292:	learn: 0.1177991	total: 776ms	remaining: 1.87s
293:	learn: 0.1177534	total: 778ms	remaining: 1.87s
294:	learn: 0.1176574	total: 780ms	remaining: 1.86s
295:	learn: 0.1175330	total: 782ms	remaining: 1.86s
296:	learn: 0.1172856	total: 784ms	remaining: 1.85s
297:	learn: 0.1171184	total: 786ms	remaining: 1.85s
298:	learn: 0.1170567	total: 788ms	remaining: 1.85s
299:	learn: 0.1169623	total: 790ms	remaining: 1.84s
300:	learn: 0.1168933	total: 792ms	remaining: 1.84s
301:	learn: 0.1167226	total: 794ms	remaining: 1.83s
302:	learn: 0.1166237	total: 796ms	remaining: 1.83s
303:	learn: 0.1165047	total: 799ms	remaining: 1.83s
304:	learn: 0.1164117	total: 801ms	remaining: 1.82s
305:	learn: 0.1162347	total: 803ms	remaining: 1.82s
306:	learn: 0.1161128	total: 805ms	remaining: 1.82s
307:	learn: 0.1160475	total: 807ms	remaining: 1.81s
308:	learn: 0.1158594	total: 810ms	remaining: 1.81s
309:	learn: 0.1157961	total: 812ms	remaining: 1.81s
310:	learn: 0.1157108	total: 814ms	remaining: 1.8s
311:	learn: 0.1156333	total: 816ms	remaining: 1.8s
312:	learn: 0.1155004	total: 818ms	remaining: 1.79s
313:	learn: 0.1153431	total: 820ms	remaining: 1.79s
314:	learn: 0.1152520	total: 822ms	remaining: 1.79s
315:	learn: 0.1151461	total: 824ms	remaining: 1.78s
316:	learn: 0.1150090	total: 826ms	remaining: 1.78s
317:	learn: 0.1149516	total: 828ms	remaining: 1.78s
318:	learn: 0.1148860	total: 830ms	remaining: 1.77s
319:	learn: 0.1147737	total: 833ms	remaining: 1.77s
320:	learn: 0.1146686	total: 835ms	remaining: 1.76s
321:	learn: 0.1145586	total: 837ms	remaining: 1.76s
322:	learn: 0.1144577	total: 839ms	remaining: 1.76s
323:	learn: 0.1144206	total: 841ms	remaining: 1.75s
324:	learn: 0.1142755	total: 843ms	remaining: 1.75s
325:	learn: 0.1142085	total: 845ms	remaining: 1.75s
326:	learn: 0.1140836	total: 847ms	remaining: 1.74s
327:	learn: 0.1139597	total: 849ms	remaining: 1.74s
328:	learn: 0.1139026	total: 851ms	remaining: 1.74s
329:	learn: 0.1138142	total: 853ms	remaining: 1.73s
330:	learn: 0.1137387	total: 855ms	remaining: 1.73s
331:	learn: 0.1135844	total: 857ms	remaining: 1.72s
332:	learn: 0.1134813	total: 859ms	remaining: 1.72s
333:	learn: 0.1134149	total: 861ms	remaining: 1.72s
334:	learn: 0.1133150	total: 863ms	remaining: 1.71s
335:	learn: 0.1131949	total: 865ms	remaining: 1.71s
336:	learn: 0.1130627	total: 867ms	remaining: 1.71s
337:	learn: 0.1130318	total: 869ms	remaining: 1.7s
338:	learn: 0.1128789	total: 871ms	remaining: 1.7s
339:	learn: 0.1127875	total: 874ms	remaining: 1.7s
340:	learn: 0.1127033	total: 875ms	remaining: 1.69s
341:	learn: 0.1125505	total: 877ms	remaining: 1.69s

In [16]:
pd.DataFrame(list(zip(model_list,accuracy_score_list)),columns=['model_name', 'accuracy_score']).sort_values(by=['accuracy_score'],ascending=False)

                model_name  accuracy_score
0      Logistic Regression        0.944623
3                      SVC        0.944623
5      AdaBoost Classifier        0.944623
1    KNeighbors Classifier        0.940610
4  RandomForest Classifier        0.940610
6           XGB Classifier        0.940610
7       CatBoostClassifier        0.939807
2  DecisionTree Classifier        0.901284